// js/xml.js — v0.9.120 — С ТЕХНИЧЕСКИМИ ОШИБКАМИ ПРИ ОТСУТСТВИИ ЛОКАЛИЗАЦИИ

const XML_VERSION = "v0.9.200";
window.XML_VERSION = XML_VERSION;

let xmlFormat = localStorage.getItem('xmlFormat') || 'pretty';

function setXMLFormat(val) {
  xmlFormat = val;
  localStorage.setItem('xmlFormat', val);
}

// Функция для безопасного получения локализации
function loc(key, fallback = '') {
  if (L[key]) return L[key];
  console.warn(`MISSING LOC KEY: ${key}`);
  return `MISSING LOC KEY: ${key}`;
}

function generateXML() {
  const eventId = document.getElementById('event-id')?.value.trim() || 'custom_event';

  let xml = `<ScriptedEvent identifier="${eventId}" commonness="100">`;

  if (xmlFormat === 'comments') {
    xml += `\n  <!-- ${loc('xmlGeneratedBy', 'Generated by Barotrauma RNG Builder v0.9.120')} -->`;
  }

  function walk(container, indent = "  ") {
    container.querySelectorAll(':scope > .node').forEach(node => {
      if (node.classList.contains('spawn')) {
        const item = node.querySelector('.item-field')?.value.trim() || 'revolver';
        const comment = xmlFormat === 'comments' ? ` <!-- ${item} -->` : '';
        xml += `\n${indent}  <SpawnAction itemidentifier="${item}" targetinventory="player" />${comment}`;
      } else if (node.classList.contains('rng')) {
        const chance = node.querySelector('.chance')?.value.trim() || '0.5';
        const chancePercent = (parseFloat(chance) * 100).toFixed(1);
        const comment = xmlFormat === 'comments' ? ` <!-- ${chancePercent}% -->` : '';
        xml += `\n${indent}  <RNGAction chance="${chance}">${comment}`;
        xml += `\n${indent}    <Success>`;
        const s = node.querySelector(`#c-${node.dataset.id}-s`);
        if (s) walk(s, indent + "      ");
        xml += `\n${indent}    </Success>`;
        xml += `\n${indent}    <Failure>`;
        const f = node.querySelector(`#c-${node.dataset.id}-f`);
        if (f) walk(f, indent + "      ");
        xml += `\n${indent}    </Failure>`;
        xml += `\n${indent}  </RNGAction>`;
      }
    });
  }

  walk(document.getElementById('root-children'));
  xml += `\n</ScriptedEvent>`;

  const full = `<Randomevents>\n  <EventPrefabs>\n    ${xml}\n  </EventPrefabs>\n</Randomevents>`;

  let output = full;
  if (xmlFormat === 'minified') {
    output = full.replace(/\n\s*/g, '');
  }

  // === ВАЛИДАЦИЯ ===
  const issues = [];

  if (localStorage.getItem('validateXML') === 'true') {
    if (!xml.includes('<SpawnAction') && !xml.includes('<RNGAction')) {
      issues.push(loc('validationEmptyEvent', 'Event is empty — nothing will spawn'));
    }

    const badChances = [...xml.matchAll(/chance="([^"]+)"/g)]
      .map(m => parseFloat(m[1]))
      .filter(c => c <= 0 || c >= 1);
    if (badChances.length > 0) {
      issues.push(loc('validationZeroChance', 'RNG with 0% or 100% chance — pointless'));
    }

    document.querySelectorAll('.node.rng').forEach(node => {
      const chance = parseFloat(node.querySelector('.chance')?.value) || 0.5;
      const id = node.dataset.id;
      const sItems = document.querySelector(`#c-${id}-s`)?.querySelectorAll('.node.spawn').length || 0;
      const fItems = document.querySelector(`#c-${id}-f`)?.querySelectorAll('.node.spawn').length || 0;

      if (sItems === 0 && fItems === 0) {
        issues.push(loc('validationNoItems', 'RNG has no items in branches'));
      }
    });
  }

  if (localStorage.getItem('checkDuplicateIDs') === 'true') {
    const ids = new Map();
    const matches = [...full.matchAll(/identifier="([^"]+)"/g)];
    for (const m of matches) {
      const id = m[1];
      if (ids.has(id)) {
        issues.push(`${loc('validationDuplicateId', 'Duplicate identifier')}: "${id}"`);
      } else {
        ids.set(id, true);
      }
    });
  }

  if (issues.length > 0) {
    let msg = loc('validationTitle', 'XML Validation — issues found:') + '\n\n' + issues.join('\n');
    msg += '\n\n' + loc('validationHint', 'These checks can be disabled in Settings → XML & Behavior');
    alert(msg);
  }

  document.getElementById('output').value = output;
}

window.generateXML = generateXML;
window.setXMLFormat = setXMLFormat;
