// js/xml.js — v0.9.99 — генерация XML с форматами и валидацией

const XML_VERSION = "v0.9.99";
window.XML_VERSION = XML_VERSION;

let xmlFormat = localStorage.getItem('xmlFormat') || 'pretty';
let validationEnabled = localStorage.getItem('validation') !== 'false';

function setXMLFormat(format) {
  xmlFormat = format;
  localStorage.setItem('xmlFormat', format);
}

function toggleValidation(enabled) {
  validationEnabled = enabled;
  localStorage.setItem('validation', enabled);
}

function generateXML() {
  const eventId = document.getElementById('event-id').value.trim() || 'custom_event';

  let xml = `<ScriptedEvent identifier="${eventId}" commonness="100">\n`;

  function walk(container, indent = "  ") {
    container.querySelectorAll(':scope > .node').forEach(node => {
      if (node.classList.contains('spawn')) {
        const itemInput = node.querySelector('.item-field');
        const item = itemInput?.value.trim() || 'revolver';
        xml += `${indent}  <SpawnAction itemidentifier="${item}" targetinventory="player" />\n`;
      } else if (node.classList.contains('rng')) {
        const chanceInput = node.querySelector('.chance');
        const chance = chanceInput?.value.trim() || '0.5';
        xml += `${indent}  <RNGAction chance="${chance}">\n`;
        xml += `${indent}    <Success>\n`;
        const successCont = node.querySelector(`#c-${node.dataset.id}-s`);
        if (successCont) walk(successCont, indent + "      ");
        xml += `${indent}    </Success>\n`;
        xml += `${indent}    <Failure>\n`;
        const failureCont = node.querySelector(`#c-${node.dataset.id}-f`);
        if (failureCont) walk(failureCont, indent + "      ");
        xml += `${indent}    </Failure>\n`;
        xml += `${indent}  </RNGAction>\n`;
      }
    });
  }

  walk(document.getElementById('root-children'));
  xml += `</ScriptedEvent>`;

  const fullXML = `<Randomevents>\n  <EventPrefabs>\n    ${xml}\n  </EventPrefabs>\n</Randomevents>`;

  // Применяем формат
  let output = fullXML;
  if (xmlFormat === 'minified') {
    output = fullXML.replace(/\n\s*/g, '');
  } else if (xmlFormat === 'comments') {
    output = `<!-- Generated by Barotrauma RNG Builder v0.9.99 -->\n` + fullXML;
  }

  // Валидация
  if (validationEnabled) {
    const issues = validateXML(output);
    if (issues.length > 0) {
      alert('Внимание! Найдены проблемы:\n• ' + issues.join('\n• '));
    }
  }

  document.getElementById('output').value = output;
}

function validateXML(xml) {
  const issues = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(xml, 'text/xml');
  const errors = doc.querySelector('parsererror');
  if (errors) issues.push('Некорректный XML');

  // Проверка дубликатов ID
  const ids = new Set();
  xml.match(/identifier="([^"]+)"/g)?.forEach(match => {
    const id = match.match(/identifier="([^"]+)"/)[1];
    if (ids.has(id)) issues.push(`Дубликат ID: ${id}`);
    ids.add(id);
  });

  // Проверка пустых событий
  if (xml.includes('<ScriptedEvent') && !xml.includes('<SpawnAction') && !xml.includes('<RNGAction')) {
    issues.push('Событие пустое');
  }

  return issues;
}

function copyXML() {
  const text = document.getElementById('output').value;
  if (!text.trim()) {
    alert('Сначала сгенерируйте XML!');
    return;
  }
  navigator.clipboard.writeText(text)
    .then(() => alert('XML скопирован!'))
    .catch(() => alert('Не удалось скопировать'));
}

function downloadXML() {
  const text = document.getElementById('output').value;
  if (!text.trim()) {
    alert('Сначала сгенерируйте XML!');
    return;
  }
  const blob = new Blob([text], { type: 'text/xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${document.getElementById('event-id').value.trim() || 'event'}.xml`;
  a.click();
  URL.revokeObjectURL(url);
}

window.generateXML = generateXML;
window.copyXML = copyXML;
window.downloadXML = downloadXML;
window.setXMLFormat = setXMLFormat;
window.toggleValidation = toggleValidation;
