export const enUiDictionary = {
    treeView: 'Tree View',
    classicView: 'Classic View',
    database: 'Database',
    documentation: 'Documentation',
    settings: 'Settings',
    theme: 'Base theme',
    themeMode: 'Theme mode',
    themeModeDark: 'Dark',
    themeModeLight: 'Light',
    themeDebug: 'Normal',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    themeStyle: 'Style overlay',
    uiScale: 'UI scale',
    grid: 'Background grid',
    projectImport: 'Import project',
    projectExport: 'Export project',
    projectStub: 'Feature stub: project import/export will be added later',
    generateXML: 'Generate XML',
    copyXML: 'Copy XML',
    downloadXML: 'Download XML',
    importXML: 'Import XML',
    addRng: '+ RNG',
    addItem: '+ Item',
    addCreature: '+ Creature',
    addAffliction: '+ Affliction',
    addEvent: '+ Event',
    addEventSet: '+ EventSet',
    clearEvent: 'Clear event',
    events: 'Events',
    rootEvent: 'Root event',
    eventId: 'Event ID',
    treeEditor: 'Tree node editor',
    selectTreeNode: 'Select a node in the tree to edit it.',
    nodeType: 'Type',
    removeNode: 'Remove node',
    duplicateNode: 'Duplicate node',
    addSuccess: 'Add to Success',
    addFailure: 'Add to Failure',
    language: 'Language',
    clearCache: 'Clear cache',
    langEnglish: 'English',
    langRussian: 'Русский',
    langSimplifiedChinese: '简体中文',
    langTraditionalChinese: '繁體中文',
    langFrench: 'Français',
    langSpanish: 'Español',
    langGerman: 'Deutsch',
    langPolish: 'Polski',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    uiScale125: '125%',
    themeStyleCompact: 'Compact',
    themeStyleBalanced: 'Balanced',
    themeStyleSoft: 'Soft',
    xmlGenerated: 'XML generated',
    xmlImported: 'XML imported',
    xmlCopied: 'XML copied',
    xmlDownloaded: 'XML downloaded',
    undo: 'Undo',
    redo: 'Redo',
    chanceColorCoding: 'Chance color coding',
    chanceInputMode: 'Chance input mode',
    chanceModeFraction: 'Fraction (0..1)',
    chanceModePercent: 'Percent (0..100)',
    treeSettings: 'Tree mode settings',
    treeSettingsBasic: 'Basic',
    treeSettingsVisual: 'Visual',
    treeSettingsAdvanced: 'Advanced',
    displayPercent: 'Probability labels',
    displayHidden: '∅',
    displayLinks: '⇄',
    displayNodes: '⋈',
    displayBoth: '⧉',
    displayHiddenHint: 'Hide probability labels',
    displayLinksHint: 'Show on links',
    displayNodesHint: 'Show near nodes',
    displayBothHint: 'Show on links and near nodes',
    autoChanceMode: 'Auto chance',
    autoChanceOff: 'Disabled',
    autoChanceRoot: 'Split only root children equally',
    autoChanceBranch: 'Split every branch equally',
    showPercentOnLinks: 'Show % on links',
    showPercentNearNodes: 'Show % near nodes',
    enableDragDrop: 'Enable drag & drop',
    snapToGrid: 'Snap to grid',
    showTreeGrid: 'Show tree grid',
    showMinimap: 'Show minimap',
    colorMinimapBranches: 'Path coloring in minimap',
    minimapPathColoring: 'Minimap path coloring',
    minimapSizePreset: 'Size preset',
    minimapScale: 'Minimap scale',
    minimapMode: 'Minimap mode',
    minimapModeStandard: 'Standard',
    minimapFocusMode: 'Focus / active path',
    minimapTypeMode: 'Node style',
    minimapTypeDots: 'Dots',
    minimapTypeColor: 'Type colors',
    minimapTypeIcon: 'Type icons',
    minimapTypeIconColor: 'Icons + colors',
    minimapSizeSmall: 'Small',
    minimapSizeMedium: 'Medium',
    minimapSizeLarge: 'Large',
    minimapSizeAuto: 'Auto',
    minimapColorNone: 'Do not display',
    minimapColorSuccessFailure: 'Success / Failure',
    minimapColorProbability: 'Probability',
    uiLevel: 'UI level',
    uiLevelBasic: 'Basic',
    uiLevelAdvanced: 'Advanced',
    modeSection: 'Mode',
    treeSettingsEditing: 'Editing',
    visualSection: 'Visual',
    debugSection: 'Debug',
    runAutoLayout: 'Run auto-layout',
    export: 'Export',
    exportTree: 'Export tree',
    exportMinimap: 'Export minimap',
    exportAsSvg: 'Export as SVG',
    exportAsPng: 'Export as PNG',
    hintAutoChance: 'Automatically redistributes child probabilities using the selected strategy.',
    hintDisplayPercent: 'Controls where probabilities are shown in the main tree.',
    hintPathColoring: 'Choose how minimap paths should be colorized.',
    showBranchNodes: 'Show intermediate branch nodes',
    showDebugBounds: 'Show debug overlays',
    gridSize: 'Grid size',
    autoLayout: 'Auto-layout',
    collapseSubtree: 'Collapse subtree',
    expandSubtree: 'Expand subtree',
    dropZoneSuccessHint: 'Drop here to insert into the first branch',
    dropZoneFailureHint: 'Drop here to insert into the second branch',
    confirmRemoveEvent: 'Delete this event?',
    smoothTreePaths: 'Smooth links',
    runSimulation: 'Run simulation',
    simulation: 'Simulation',
    validateTree: 'Validate tree',
    toggleHeatmap: 'Heatmap',
    searchNodes: 'Search nodes',
    quickAdd: 'Quick add',
    nodeMode: 'Node',
    treeMode: 'Tree',
    search: 'Search',
    iterations: 'Iterations',
    seed: 'Seed',
    confirmClearEvent: 'Clear the current event?',
    confirmRemoveNode: 'Remove this node?',
    importXmlPlaceholderDescription: 'Placeholder import dialog: upload an XML file, drag it here, or paste XML directly. Import logic will be added later.',
    importXmlDropTitle: 'Drop an XML file here or click to upload',
    importXmlDropHint: 'Accepted for now: .xml files (placeholder only)',
    importXmlNoFile: 'No file selected',
    importXmlPasteLabel: 'Paste XML code',
    importXmlPastePlaceholder: '<Event identifier="example">\n  ...\n</Event>',
    importXmlActionPlaceholder: 'Import placeholder',
    projectImportPlaceholderDescription: 'Placeholder import dialog: upload a project file or drag it here. Manual JSON input is intentionally disabled.',
    projectImportDropHint: 'Accepted for now: .json project files (placeholder only)',
    projectImportActionPlaceholder: 'Import project (placeholder)',
    hideTreeSummaryPanel: 'Hide summary panel',
    showTreeSummaryPanel: 'Show summary panel',
    hideTreeSettingsPanel: 'Hide settings panel',
    showTreeSettingsPanel: 'Show settings panel',
    close: 'Close',
    localizationPlaceholder: 'Localization placeholder: this language is not implemented yet.',
    menuFile: 'File',
    menuProjectGroup: 'Project',
    menuXmlGroup: 'XML',
    menuEdit: 'Edit',
    menuPresets: 'Presets',
    menuTools: 'Tools',
    menuView: 'View',
    menuHelp: 'Help',
    menuSettings: 'Settings',
    menuDeleteSelected: 'Delete selected node',
    menuDuplicateSelected: 'Duplicate selected node',
    menuBasePresets: 'Base presets',
    menuOutpostMission: 'Outpost mission',
    menuWreckExpedition: 'Wreck expedition',
    loadPreset: 'Load preset',
    savePreset: 'Save as preset',
    managePreset: 'Manage presets',
    probabilityAnalysis: 'Probability analysis',
    menuTheme: 'Theme',
    menuStyle: 'Style',
    menuUiScale: 'UI scale',
    openWiki: 'Wiki',
    openGithub: 'GitHub',
    reportIssue: 'Issues',
    aboutApp: 'About',
    openSettingsLanguage: 'Language settings',
    openSettingsXmlBehavior: 'XML behavior',
    resetSettings: 'Reset settings',
    confirm: 'Confirm',
    cancel: 'Cancel',
    sfAccentPalette: 'S/F accents',
    sfAccentPaletteFull: 'Success / Failure accent palette',
    sfAccentDefault: 'Emerald / Crimson',
    sfAccentMintRose: 'Mint / Amber',
    sfAccentNeonCherry: 'Blue / Pink',
    sfAccentForestRuby: 'Violet / Gold',
    build: 'Build',
    output: 'Output',
    outputXmlTab: 'XML',
    outputPanelExpand: '▶ {label}',
    outputPanelCollapse: '▼ {label}',
    editorModeBasic: 'Basic',
    editorModeIntermediate: 'Intermediate',
    editorModeAdvanced: 'Advanced',
    treeOutlineLabel: 'Tree outline',
    outputTabsLabel: 'Output tabs',
    editorOperationMode: 'Editor operation mode',
    treeWindowMode: 'Window mode',
    editorViewMode: 'Editor view mode',
    docsGroupsLabel: 'Documentation groups',
    searchDocumentationPlaceholder: 'Search documentation...',
    result: 'Result',
    count: 'Count',
    simulatedProbability: 'Simulated probability',
    exactProbability: 'Exact probability',
    aboutTitle: 'About',
    aboutHeading: 'Barotrauma RNG Builder',
    aboutBody1: 'Visual editor for Barotrauma random event graphs.',
    aboutBody2: 'Includes Tree mode, XML generation, simulation, and reference tools.',
    noTerminalSpawnNodes: 'No terminal action nodes in the current tree.',
    addChild: 'Add child',
    copySubtree: 'Copy subtree',
    pasteSubtree: 'Paste subtree',
    failedLoadDatabase: 'Failed to load database',
    dbLoadError: 'Database loading error',
    selectNodeDelete: 'Select a node to delete.',
    selectNodeDuplicate: 'Select a node to duplicate.',
    simulationCompletedEmpty: 'Simulation completed: the tree is empty.',
    validationNoIssues: 'Validation completed: no issues found.',
    quickAddPrompt: 'Quick add node type ({types})',
    unknownNodeTypeForMode: 'Unknown node type for the current editor mode.',
    featureUpcoming: 'This feature will be available in an upcoming update.',
    basePresetPlaceholder: 'Base preset placeholder.',
    renameEventHint: 'Double click to rename',
    eventTabAdd: 'Add event',
    treeSummary: 'Tree summary',
    treeSummaryHint: 'Root stays expanded while deeper levels auto-collapse for readability.',
    treeSummaryEmpty: 'Add nodes to see the tree outline.',
    treeLeafNode: 'Leaf node',
    treeExpandChildren: 'Expand children',
    treeCollapseChildren: 'Collapse children',
    treeTypeTooltip: 'Type: {type}',
    treeNodeIdTooltip: 'Node identifier {id}',
    treeOutlineChance: 'Chance',
    treeOutlineBranches: 'Branches',
    treeOutlineIdentifier: 'Identifier',
    treeOutlineConditions: 'Conditions',
    treeOutlineAction: 'Action',
    treeUnnamedEventSet: 'unnamed event set',
    treeUnnamedEvent: 'unnamed event',
    treeNoConditions: 'No conditions',
    treeUnknownItem: 'unknown item',
    treeUnknownCreature: 'unknown creature',
    treeUnknownAffliction: 'unknown affliction',
    unsetValue: 'unset',
    anyValue: 'any',
    treeBranchCount: '{count} branch',
    treeBranchCountPlural: '{count} branches',
    treeInspectorHint: 'Pan: drag · Zoom: mouse wheel · Minimap: drag header / resize corner / wheel zoom · Click a minimap node to jump.',
    treeSettingsCollapse: 'Collapse settings',
    treeSettingsExpand: 'Expand settings',
    minimapTitle: 'Minimap',
    chance: 'Chance',
    mode: 'Mode',
    probability: 'Probability',
    weight: 'Weight',
    identifier: 'Identifier',
    commonness: 'Commonness',
    eventCount: 'Event count',
    chooseRandom: 'Choose random',
    minIntensity: 'Min intensity',
    maxIntensity: 'Max intensity',
    minDifficulty: 'Min difficulty',
    maxDifficulty: 'Max difficulty',
    allowAtStart: 'Allow at start',
    perWreck: 'Per wreck',
    perRuin: 'Per ruin',
    perCave: 'Per cave',
    ignoreCooldown: 'Ignore cooldown',
    triggerCooldown: 'Trigger cooldown',
    identity: 'Identity',
    conditions: 'Conditions',
    behavior: 'Behavior',
    amount: 'Amount',
    quality: 'Quality',
    count: 'Count',
    spawnLocation: 'Spawn location',
    spawnLocationInside: 'inside',
    spawnLocationOutside: 'outside',
    spawnLocationNear: 'near',
    label: 'Label',
    value: 'Value',
    removeBranch: 'Remove branch',
    children: 'Children',
    branch: 'Branch',
    strength: 'Strength'
};
