import { sharedLanguageNames } from './shared-language-names.js';

export const esUiDictionary = {
  menuFile: 'Archivo',
  projectImport: 'Importar proyecto',
  projectExport: 'Exportar proyecto',
  importXML: 'Importar XML',
  downloadXML: 'Descargar XML',
  generateXML: 'Generar XML',
  menuEdit: 'Editar',
  undo: 'Deshacer',
  redo: 'Rehacer',
  menuDeleteSelected: 'Eliminar nodo seleccionado',
  menuDuplicateSelected: 'Duplicar nodo seleccionado',
  clearEvent: 'Limpiar evento',
  menuPresets: 'Preajustes',
  menuBasePresets: 'Preajustes base',
  menuOutpostMission: 'Misión de puesto',
  menuWreckExpedition: 'Expedición al pecio',
  loadPreset: 'Cargar preajuste',
  savePreset: 'Guardar como preajuste',
  managePreset: 'Administrar preajustes',
  menuTools: 'Herramientas',
  simulation: 'Simulación',
  validateTree: 'Validar árbol',
  probabilityAnalysis: 'Análisis de probabilidad',
  menuView: 'Vista',
  menuTheme: 'Modo de tema',
  themeModeDark: 'Oscuro',
  themeModeLight: 'Claro',
  menuStyle: 'Estilo',
  themeDebug: 'Estándar',
  themeClassicLuna: 'Classic Luna',
  themeNeonOps: 'Neon Ops',
  themeRetroTerminal: 'Retro Terminal',
  themeSoftBloom: 'Soft Bloom',
  menuUiScale: 'Escala UI',
  uiScale80: '80%',
  uiScale90: '90%',
  uiScale100: '100%',
  uiScale110: '110%',
  uiScale120: '120%',
  menuHelp: 'Ayuda',
  documentation: 'Documentación',
  openWiki: 'Abrir Wiki',
  openGithub: 'Abrir GitHub',
  reportIssue: 'Reportar problema',
  aboutApp: 'Acerca de',
  menuSettings: 'Ajustes',
  language: 'Idioma',
  openSettingsXmlBehavior: 'Comportamiento XML',
  resetSettings: 'Restablecer ajustes',
  database: 'Base de datos',
  editorModeBasic: 'Básico',
  editorModeIntermediate: 'Intermedio',
  editorModeAdvanced: 'Avanzado',
  nodeMode: 'Nodo',
  treeMode: 'Árbol',
  editorOperationMode: 'Modo del editor',
  editorViewMode: 'Vista del editor',
  ...sharedLanguageNames
};
