import { sharedLanguageNames } from './shared-language-names.js';

export const frUiDictionary = {
  menuFile: 'Fichier',
  projectImport: 'Importer le projet',
  projectExport: 'Exporter le projet',
  importXML: 'Importer XML',
  downloadXML: 'Télécharger XML',
  generateXML: 'Générer XML',
  menuEdit: 'Édition',
  undo: 'Annuler',
  redo: 'Rétablir',
  menuDeleteSelected: 'Supprimer le nœud sélectionné',
  menuDuplicateSelected: 'Dupliquer le nœud sélectionné',
  clearEvent: 'Vider l’événement',
  menuPresets: 'Préréglages',
  menuBasePresets: 'Préréglages de base',
  menuOutpostMission: 'Mission d’avant-poste',
  menuWreckExpedition: 'Expédition d’épave',
  loadPreset: 'Charger un préréglage',
  savePreset: 'Enregistrer comme préréglage',
  managePreset: 'Gérer les préréglages',
  menuTools: 'Outils',
  simulation: 'Simulation',
  validateTree: 'Valider l’arbre',
  probabilityAnalysis: 'Analyse de probabilité',
  menuView: 'Affichage',
  menuTheme: 'Mode du thème',
  themeModeDark: 'Sombre',
  themeModeLight: 'Clair',
  menuStyle: 'Style',
  themeDebug: 'Standard',
  themeClassicLuna: 'Classic Luna',
  themeNeonOps: 'Neon Ops',
  themeRetroTerminal: 'Retro Terminal',
  themeSoftBloom: 'Soft Bloom',
  menuUiScale: 'Échelle UI',
  uiScale80: '80%',
  uiScale90: '90%',
  uiScale100: '100%',
  uiScale110: '110%',
  uiScale120: '120%',
  menuHelp: 'Aide',
  documentation: 'Documentation',
  openWiki: 'Ouvrir le Wiki',
  openGithub: 'Ouvrir GitHub',
  reportIssue: 'Signaler un problème',
  aboutApp: 'À propos',
  menuSettings: 'Paramètres',
  language: 'Langue',
  openSettingsXmlBehavior: 'Comportement XML',
  resetSettings: 'Réinitialiser les paramètres',
  database: 'Base de données',
  editorModeBasic: 'Basique',
  editorModeIntermediate: 'Intermédiaire',
  editorModeAdvanced: 'Avancé',
  nodeMode: 'Nœud',
  treeMode: 'Arbre',
  editorOperationMode: 'Mode éditeur',
  editorViewMode: 'Vue éditeur',
  ...sharedLanguageNames
};
