const sharedLanguageNames = {
  langEnglish: 'English',
  langSimplifiedChinese: '简体中文',
  langTraditionalChinese: '繁體中文',
  langRussian: 'Русский',
  langFrench: 'Français',
  langSpanish: 'Español',
  langGerman: 'Deutsch',
  langPolish: 'Polski'
};

export const menuOnlyDictionaries = {
  'zh-Hans': {
    menuFile: '文件',
    projectImport: '导入项目',
    projectExport: '导出项目',
    importXML: '导入 XML',
    downloadXML: '下载 XML',
    generateXML: '生成 XML',
    menuEdit: '编辑',
    undo: '撤销',
    redo: '重做',
    menuDeleteSelected: '删除所选节点',
    menuDuplicateSelected: '复制所选节点',
    clearEvent: '清空事件',
    menuPresets: '预设',
    menuBasePresets: '基础预设',
    menuOutpostMission: '前哨任务',
    menuWreckExpedition: '沉船探险',
    loadPreset: '加载预设',
    savePreset: '保存为预设',
    managePreset: '管理预设',
    menuTools: '工具',
    simulation: '模拟',
    validateTree: '校验树',
    probabilityAnalysis: '概率分析',
    menuView: '视图',
    menuTheme: '主题模式',
    themeModeDark: '深色',
    themeModeLight: '浅色',
    menuStyle: '样式',
    themeDebug: '标准',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: '界面缩放',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: '帮助',
    documentation: '文档',
    openWiki: '打开 Wiki',
    openGithub: '打开 GitHub',
    reportIssue: '报告问题',
    aboutApp: '关于',
    menuSettings: '设置',
    language: '语言',
    openSettingsXmlBehavior: 'XML 行为',
    resetSettings: '重置设置',
    database: '数据库',
    editorModeBasic: '基础',
    editorModeIntermediate: '中级',
    editorModeAdvanced: '高级',
    nodeMode: '节点',
    treeMode: '树',
    editorOperationMode: '编辑器模式',
    editorViewMode: '编辑视图',
    ...sharedLanguageNames
  },
  'zh-Hant': {
    menuFile: '檔案',
    projectImport: '匯入專案',
    projectExport: '匯出專案',
    importXML: '匯入 XML',
    downloadXML: '下載 XML',
    generateXML: '產生 XML',
    menuEdit: '編輯',
    undo: '復原',
    redo: '重做',
    menuDeleteSelected: '刪除選取節點',
    menuDuplicateSelected: '複製選取節點',
    clearEvent: '清空事件',
    menuPresets: '預設',
    menuBasePresets: '基礎預設',
    menuOutpostMission: '前哨站任務',
    menuWreckExpedition: '沉船探勘',
    loadPreset: '載入預設',
    savePreset: '儲存為預設',
    managePreset: '管理預設',
    menuTools: '工具',
    simulation: '模擬',
    validateTree: '驗證樹',
    probabilityAnalysis: '機率分析',
    menuView: '檢視',
    menuTheme: '主題模式',
    themeModeDark: '深色',
    themeModeLight: '淺色',
    menuStyle: '樣式',
    themeDebug: '標準',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: '介面縮放',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: '說明',
    documentation: '文件',
    openWiki: '開啟 Wiki',
    openGithub: '開啟 GitHub',
    reportIssue: '回報問題',
    aboutApp: '關於',
    menuSettings: '設定',
    language: '語言',
    openSettingsXmlBehavior: 'XML 行為',
    resetSettings: '重設設定',
    database: '資料庫',
    editorModeBasic: '基礎',
    editorModeIntermediate: '中階',
    editorModeAdvanced: '進階',
    nodeMode: '節點',
    treeMode: '樹',
    editorOperationMode: '編輯器模式',
    editorViewMode: '編輯視圖',
    ...sharedLanguageNames
  },
  fr: {
    menuFile: 'Fichier',
    projectImport: 'Importer le projet',
    projectExport: 'Exporter le projet',
    importXML: 'Importer XML',
    downloadXML: 'Télécharger XML',
    generateXML: 'Générer XML',
    menuEdit: 'Édition',
    undo: 'Annuler',
    redo: 'Rétablir',
    menuDeleteSelected: 'Supprimer le nœud sélectionné',
    menuDuplicateSelected: 'Dupliquer le nœud sélectionné',
    clearEvent: 'Vider l’événement',
    menuPresets: 'Préréglages',
    menuBasePresets: 'Préréglages de base',
    menuOutpostMission: 'Mission d’avant-poste',
    menuWreckExpedition: 'Expédition d’épave',
    loadPreset: 'Charger un préréglage',
    savePreset: 'Enregistrer comme préréglage',
    managePreset: 'Gérer les préréglages',
    menuTools: 'Outils',
    simulation: 'Simulation',
    validateTree: 'Valider l’arbre',
    probabilityAnalysis: 'Analyse de probabilité',
    menuView: 'Affichage',
    menuTheme: 'Mode du thème',
    themeModeDark: 'Sombre',
    themeModeLight: 'Clair',
    menuStyle: 'Style',
    themeDebug: 'Standard',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: 'Échelle UI',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: 'Aide',
    documentation: 'Documentation',
    openWiki: 'Ouvrir le Wiki',
    openGithub: 'Ouvrir GitHub',
    reportIssue: 'Signaler un problème',
    aboutApp: 'À propos',
    menuSettings: 'Paramètres',
    language: 'Langue',
    openSettingsXmlBehavior: 'Comportement XML',
    resetSettings: 'Réinitialiser les paramètres',
    database: 'Base de données',
    editorModeBasic: 'Basique',
    editorModeIntermediate: 'Intermédiaire',
    editorModeAdvanced: 'Avancé',
    nodeMode: 'Nœud',
    treeMode: 'Arbre',
    editorOperationMode: 'Mode éditeur',
    editorViewMode: 'Vue éditeur',
    ...sharedLanguageNames
  },
  es: {
    menuFile: 'Archivo',
    projectImport: 'Importar proyecto',
    projectExport: 'Exportar proyecto',
    importXML: 'Importar XML',
    downloadXML: 'Descargar XML',
    generateXML: 'Generar XML',
    menuEdit: 'Editar',
    undo: 'Deshacer',
    redo: 'Rehacer',
    menuDeleteSelected: 'Eliminar nodo seleccionado',
    menuDuplicateSelected: 'Duplicar nodo seleccionado',
    clearEvent: 'Limpiar evento',
    menuPresets: 'Preajustes',
    menuBasePresets: 'Preajustes base',
    menuOutpostMission: 'Misión de puesto',
    menuWreckExpedition: 'Expedición al pecio',
    loadPreset: 'Cargar preajuste',
    savePreset: 'Guardar como preajuste',
    managePreset: 'Administrar preajustes',
    menuTools: 'Herramientas',
    simulation: 'Simulación',
    validateTree: 'Validar árbol',
    probabilityAnalysis: 'Análisis de probabilidad',
    menuView: 'Vista',
    menuTheme: 'Modo de tema',
    themeModeDark: 'Oscuro',
    themeModeLight: 'Claro',
    menuStyle: 'Estilo',
    themeDebug: 'Estándar',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: 'Escala UI',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: 'Ayuda',
    documentation: 'Documentación',
    openWiki: 'Abrir Wiki',
    openGithub: 'Abrir GitHub',
    reportIssue: 'Reportar problema',
    aboutApp: 'Acerca de',
    menuSettings: 'Ajustes',
    language: 'Idioma',
    openSettingsXmlBehavior: 'Comportamiento XML',
    resetSettings: 'Restablecer ajustes',
    database: 'Base de datos',
    editorModeBasic: 'Básico',
    editorModeIntermediate: 'Intermedio',
    editorModeAdvanced: 'Avanzado',
    nodeMode: 'Nodo',
    treeMode: 'Árbol',
    editorOperationMode: 'Modo del editor',
    editorViewMode: 'Vista del editor',
    ...sharedLanguageNames
  },
  de: {
    menuFile: 'Datei',
    projectImport: 'Projekt importieren',
    projectExport: 'Projekt exportieren',
    importXML: 'XML importieren',
    downloadXML: 'XML herunterladen',
    generateXML: 'XML erzeugen',
    menuEdit: 'Bearbeiten',
    undo: 'Rückgängig',
    redo: 'Wiederholen',
    menuDeleteSelected: 'Ausgewählten Knoten löschen',
    menuDuplicateSelected: 'Ausgewählten Knoten duplizieren',
    clearEvent: 'Ereignis leeren',
    menuPresets: 'Voreinstellungen',
    menuBasePresets: 'Basis-Voreinstellungen',
    menuOutpostMission: 'Außenpostenmission',
    menuWreckExpedition: 'Wrackexpedition',
    loadPreset: 'Voreinstellung laden',
    savePreset: 'Als Voreinstellung speichern',
    managePreset: 'Voreinstellungen verwalten',
    menuTools: 'Werkzeuge',
    simulation: 'Simulation',
    validateTree: 'Baum validieren',
    probabilityAnalysis: 'Wahrscheinlichkeitsanalyse',
    menuView: 'Ansicht',
    menuTheme: 'Themenmodus',
    themeModeDark: 'Dunkel',
    themeModeLight: 'Hell',
    menuStyle: 'Stil',
    themeDebug: 'Standard',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: 'UI-Skalierung',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: 'Hilfe',
    documentation: 'Dokumentation',
    openWiki: 'Wiki öffnen',
    openGithub: 'GitHub öffnen',
    reportIssue: 'Problem melden',
    aboutApp: 'Über',
    menuSettings: 'Einstellungen',
    language: 'Sprache',
    openSettingsXmlBehavior: 'XML-Verhalten',
    resetSettings: 'Einstellungen zurücksetzen',
    database: 'Datenbank',
    editorModeBasic: 'Einfach',
    editorModeIntermediate: 'Mittel',
    editorModeAdvanced: 'Erweitert',
    nodeMode: 'Knoten',
    treeMode: 'Baum',
    editorOperationMode: 'Editormodus',
    editorViewMode: 'Editoransicht',
    ...sharedLanguageNames
  },
  pl: {
    menuFile: 'Plik',
    projectImport: 'Importuj projekt',
    projectExport: 'Eksportuj projekt',
    importXML: 'Importuj XML',
    downloadXML: 'Pobierz XML',
    generateXML: 'Generuj XML',
    menuEdit: 'Edycja',
    undo: 'Cofnij',
    redo: 'Ponów',
    menuDeleteSelected: 'Usuń zaznaczony węzeł',
    menuDuplicateSelected: 'Duplikuj zaznaczony węzeł',
    clearEvent: 'Wyczyść wydarzenie',
    menuPresets: 'Presety',
    menuBasePresets: 'Presety bazowe',
    menuOutpostMission: 'Misja posterunku',
    menuWreckExpedition: 'Ekspedycja wraku',
    loadPreset: 'Wczytaj preset',
    savePreset: 'Zapisz jako preset',
    managePreset: 'Zarządzaj presetami',
    menuTools: 'Narzędzia',
    simulation: 'Symulacja',
    validateTree: 'Waliduj drzewo',
    probabilityAnalysis: 'Analiza prawdopodobieństwa',
    menuView: 'Widok',
    menuTheme: 'Tryb motywu',
    themeModeDark: 'Ciemny',
    themeModeLight: 'Jasny',
    menuStyle: 'Styl',
    themeDebug: 'Standard',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    menuUiScale: 'Skala UI',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    menuHelp: 'Pomoc',
    documentation: 'Dokumentacja',
    openWiki: 'Otwórz Wiki',
    openGithub: 'Otwórz GitHub',
    reportIssue: 'Zgłoś problem',
    aboutApp: 'O aplikacji',
    menuSettings: 'Ustawienia',
    language: 'Język',
    openSettingsXmlBehavior: 'Zachowanie XML',
    resetSettings: 'Resetuj ustawienia',
    database: 'Baza danych',
    editorModeBasic: 'Podstawowy',
    editorModeIntermediate: 'Pośredni',
    editorModeAdvanced: 'Zaawansowany',
    nodeMode: 'Węzeł',
    treeMode: 'Drzewo',
    editorOperationMode: 'Tryb edytora',
    editorViewMode: 'Widok edytora',
    ...sharedLanguageNames
  }
};
