import { sharedLanguageNames } from './shared-language-names.js';

export const plUiDictionary = {
  menuFile: 'Plik',
  projectImport: 'Importuj projekt',
  projectExport: 'Eksportuj projekt',
  importXML: 'Importuj XML',
  downloadXML: 'Pobierz XML',
  generateXML: 'Generuj XML',
  menuEdit: 'Edycja',
  undo: 'Cofnij',
  redo: 'Ponów',
  menuDeleteSelected: 'Usuń zaznaczony węzeł',
  menuDuplicateSelected: 'Duplikuj zaznaczony węzeł',
  clearEvent: 'Wyczyść wydarzenie',
  menuPresets: 'Presety',
  menuBasePresets: 'Presety bazowe',
  menuOutpostMission: 'Misja posterunku',
  menuWreckExpedition: 'Ekspedycja wraku',
  loadPreset: 'Wczytaj preset',
  savePreset: 'Zapisz jako preset',
  managePreset: 'Zarządzaj presetami',
  menuTools: 'Narzędzia',
  simulation: 'Symulacja',
  validateTree: 'Waliduj drzewo',
  probabilityAnalysis: 'Analiza prawdopodobieństwa',
  menuView: 'Widok',
  menuTheme: 'Tryb motywu',
  themeModeDark: 'Ciemny',
  themeModeLight: 'Jasny',
  menuStyle: 'Styl',
  themeDebug: 'Standard',
  themeClassicLuna: 'Classic Luna',
  themeNeonOps: 'Neon Ops',
  themeRetroTerminal: 'Retro Terminal',
  themeSoftBloom: 'Soft Bloom',
  menuUiScale: 'Skala UI',
  uiScale80: '80%',
  uiScale90: '90%',
  uiScale100: '100%',
  uiScale110: '110%',
  uiScale120: '120%',
  menuHelp: 'Pomoc',
  documentation: 'Dokumentacja',
  openWiki: 'Otwórz Wiki',
  openGithub: 'Otwórz GitHub',
  reportIssue: 'Zgłoś problem',
  aboutApp: 'O aplikacji',
  menuSettings: 'Ustawienia',
  language: 'Język',
  openSettingsXmlBehavior: 'Zachowanie XML',
  resetSettings: 'Resetuj ustawienia',
  database: 'Baza danych',
  editorModeBasic: 'Podstawowy',
  editorModeIntermediate: 'Pośredni',
  editorModeAdvanced: 'Zaawansowany',
  nodeMode: 'Węzeł',
  treeMode: 'Drzewo',
  editorOperationMode: 'Tryb edytora',
  editorViewMode: 'Widok edytora',
  ...sharedLanguageNames
};
