export const ruUiDictionary = {
    treeView: 'Вид дерева',
    classicView: 'Классический вид',
    database: 'База данных',
    documentation: 'Документация',
    settings: 'Настройки',
    theme: 'Базовая тема',
    themeMode: 'Режим темы',
    themeModeDark: 'Тёмная',
    themeModeLight: 'Светлая',
    themeDebug: 'Normal',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    themeStyle: 'Надстройка темы',
    uiScale: 'Масштаб UI',
    grid: 'Фоновая сетка',
    projectImport: 'Импорт проекта',
    projectExport: 'Экспорт проекта',
    projectStub: 'Заглушка: импорт и экспорт проекта появятся позже',
    generateXML: 'Сгенерировать XML',
    copyXML: 'Копировать XML',
    downloadXML: 'Скачать XML',
    importXML: 'Импорт XML',
    addRng: '+ RNG',
    addItem: '+ Предмет',
    addCreature: '+ Существо',
    addAffliction: '+ Аффликт',
    addEvent: '+ Event',
    addEventSet: '+ EventSet',
    clearEvent: 'Очистить событие',
    events: 'События',
    rootEvent: 'Корневое событие',
    eventId: 'ID события',
    treeEditor: 'Редактор Tree-узлов',
    selectTreeNode: 'Выберите узел в дереве, чтобы редактировать его.',
    nodeType: 'Тип',
    removeNode: 'Удалить узел',
    duplicateNode: 'Дублировать узел',
    addSuccess: 'Добавить в Success',
    addFailure: 'Добавить в Failure',
    language: 'Язык',
    clearCache: 'Очистить кэш',
    langEnglish: 'English',
    langRussian: 'Русский',
    langSimplifiedChinese: '简体中文',
    langTraditionalChinese: '繁體中文',
    langFrench: 'Français',
    langSpanish: 'Español',
    langGerman: 'Deutsch',
    langPolish: 'Polski',
    uiScale80: '80%',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale120: '120%',
    uiScale125: '125%',
    themeStyleCompact: 'Компактная',
    themeStyleBalanced: 'Сбалансированная',
    themeStyleSoft: 'Мягкая',
    xmlGenerated: 'XML сгенерирован',
    xmlImported: 'XML импортирован',
    xmlCopied: 'XML скопирован',
    xmlDownloaded: 'XML скачан',
    undo: 'Отменить',
    redo: 'Повторить',
    chanceColorCoding: 'Цветовая кодировка шансов',
    chanceInputMode: 'Формат ввода шанса',
    chanceModeFraction: 'Дробь (0..1)',
    chanceModePercent: 'Проценты (0..100)',
    treeSettings: 'Настройки Tree режима',
    treeSettingsBasic: 'Базовые',
    treeSettingsVisual: 'Визуал',
    treeSettingsAdvanced: 'Расширенные',
    displayPercent: 'Подписи вероятностей',
    displayHidden: '∅',
    displayLinks: '⇄',
    displayNodes: '⋈',
    displayBoth: '⧉',
    displayHiddenHint: 'Скрыть подписи вероятностей',
    displayLinksHint: 'Показывать на связях',
    displayNodesHint: 'Показывать возле узлов',
    displayBothHint: 'Показывать и на связях, и возле узлов',
    autoChanceMode: 'Авто-шанс',
    autoChanceOff: 'Отключён',
    autoChanceRoot: 'Делить только корневые дочерние узлы поровну',
    autoChanceBranch: 'Делить каждую ветку поровну',
    showPercentOnLinks: 'Показывать % на связях',
    showPercentNearNodes: 'Показывать % возле узлов',
    enableDragDrop: 'Включить drag & drop',
    snapToGrid: 'Привязка к сетке',
    showTreeGrid: 'Показывать сетку дерева',
    showMinimap: 'Показывать миникарту',
    colorMinimapBranches: 'Подсветка путей на миникарте',
    minimapPathColoring: 'Подсветка путей миникарты',
    minimapSizePreset: 'Размер',
    minimapScale: 'Масштаб миникарты',
    minimapMode: 'Режим миникарты',
    minimapModeStandard: 'Стандартный',
    minimapFocusMode: 'Фокус / активный путь',
    minimapTypeMode: 'Стиль узлов',
    minimapTypeDots: 'Точки',
    minimapTypeColor: 'Цвета типов',
    minimapTypeIcon: 'Иконки типов',
    minimapTypeIconColor: 'Иконки + цвета',
    minimapSizeSmall: 'Маленький',
    minimapSizeMedium: 'Средний',
    minimapSizeLarge: 'Большой',
    minimapSizeAuto: 'Авто',
    minimapColorSuccessFailure: 'Успех / неудача',
    minimapColorProbability: 'Вероятность',
    uiLevel: 'Уровень интерфейса',
    uiLevelBasic: 'Базовый',
    uiLevelAdvanced: 'Расширенный',
    modeSection: 'Режим',
    treeSettingsEditing: 'Редактирование',
    visualSection: 'Визуал',
    debugSection: 'Отладка',
    runAutoLayout: 'Запустить авто-раскладку',
    export: 'Экспорт',
    exportTree: 'Экспорт дерева',
    exportMinimap: 'Экспорт миникарты',
    exportAsSvg: 'Экспорт в SVG',
    exportAsPng: 'Экспорт в PNG',
    hintAutoChance: 'Автоматически перераспределяет вероятности дочерних узлов по выбранной стратегии.',
    hintDisplayPercent: 'Определяет, где показываются вероятности в основном дереве.',
    hintPathColoring: 'Выберите, как раскрашивать пути на миникарте.',
    showBranchNodes: 'Показывать промежуточные узлы веток',
    showDebugBounds: 'Показывать debug-оверлеи',
    gridSize: 'Размер сетки',
    autoLayout: 'Авто-раскладка',
    collapseSubtree: 'Свернуть поддерево',
    expandSubtree: 'Развернуть поддерево',
    dropZoneSuccessHint: 'Отпустите сюда, чтобы вставить в первую ветку',
    dropZoneFailureHint: 'Отпустите сюда, чтобы вставить во вторую ветку',
    confirmRemoveEvent: 'Удалить это событие?',
    smoothTreePaths: 'Плавные связи',
    runSimulation: 'Запустить симуляцию',
    simulation: 'Симуляция',
    validateTree: 'Проверить дерево',
    toggleHeatmap: 'Тепловая карта',
    searchNodes: 'Поиск узлов',
    quickAdd: 'Быстрое добавление',
    nodeMode: 'Узлы',
    treeMode: 'Tree',
    search: 'Поиск',
    iterations: 'Итерации',
    seed: 'Seed',
    confirmClearEvent: 'Очистить текущее событие?',
    confirmRemoveNode: 'Удалить этот узел?',
    importXmlPlaceholderDescription: 'Диалог импорта пока работает как заглушка: загрузите XML-файл, перетащите его сюда или вставьте XML напрямую. Логика импорта появится позже.',
    importXmlDropTitle: 'Перетащите XML-файл сюда или нажмите для загрузки',
    importXmlDropHint: 'Пока принимаются только .xml файлы (заглушка)',
    importXmlNoFile: 'Файл не выбран',
    importXmlPasteLabel: 'Вставьте XML-код',
    importXmlPastePlaceholder: '<Event identifier="example">\n  ...\n</Event>',
    importXmlActionPlaceholder: 'Заглушка импорта',
    close: 'Закрыть',
    localizationPlaceholder: 'Заглушка локализации: этот язык пока не реализован.',
    menuFile: 'Файл',
    menuEdit: 'Правка',
    menuPresets: 'Пресеты',
    menuTools: 'Инструменты',
    menuView: 'Вид',
    menuHelp: 'Справка',
    menuSettings: 'Настройки',
    menuDeleteSelected: 'Удалить выбранный узел',
    menuDuplicateSelected: 'Дублировать выбранный узел',
    menuBasePresets: 'Базовые пресеты',
    menuOutpostMission: 'Миссия аванпоста',
    menuWreckExpedition: 'Экспедиция к обломкам',
    loadPreset: 'Загрузить пресет',
    savePreset: 'Сохранить как пресет',
    managePreset: 'Управление пресетами',
    probabilityAnalysis: 'Анализ вероятностей',
    menuTheme: 'Тема',
    menuStyle: 'Стиль',
    menuUiScale: 'Масштаб UI',
    openWiki: 'Wiki',
    openGithub: 'GitHub',
    reportIssue: 'Issues',
    aboutApp: 'О программе',
    openSettingsLanguage: 'Настройки языка',
    openSettingsXmlBehavior: 'Поведение XML',
    resetSettings: 'Сбросить настройки',
    build: 'Сборка',
    output: 'Вывод',
    outputXmlTab: 'XML',
    outputPanelExpand: '▶ {label}',
    outputPanelCollapse: '▼ {label}',
    editorModeBasic: 'Basic',
    editorModeIntermediate: 'Intermediate',
    editorModeAdvanced: 'Advanced',
    treeOutlineLabel: 'Структура дерева',
    outputTabsLabel: 'Вкладки вывода',
    editorOperationMode: 'Режим работы редактора',
    editorViewMode: 'Режим отображения редактора',
    docsGroupsLabel: 'Группы документации',
    searchDocumentationPlaceholder: 'Поиск по документации...',
    result: 'Результат',
    count: 'Количество',
    simulatedProbability: 'Смоделированная вероятность',
    exactProbability: 'Точная вероятность',
    aboutTitle: 'О программе',
    aboutHeading: 'Barotrauma RNG Builder',
    aboutBody1: 'Визуальный редактор графов случайных событий для Barotrauma.',
    aboutBody2: 'Включает Tree режим, генерацию XML, симуляцию и справочные инструменты.',
    noTerminalSpawnNodes: 'В текущем дереве нет конечных action-узлов.',
    addChild: 'Добавить дочерний узел',
    copySubtree: 'Копировать поддерево',
    pasteSubtree: 'Вставить поддерево',
    failedLoadDatabase: 'Не удалось загрузить базу данных',
    dbLoadError: 'Ошибка загрузки базы данных',
    selectNodeDelete: 'Выберите узел для удаления.',
    selectNodeDuplicate: 'Выберите узел для дублирования.',
    simulationCompletedEmpty: 'Симуляция завершена: дерево пустое.',
    validationNoIssues: 'Проверка завершена: проблем не найдено.',
    quickAddPrompt: 'Быстро добавить тип узла ({types})',
    unknownNodeTypeForMode: 'Неизвестный тип узла для текущего режима редактора.',
    featureUpcoming: 'Эта функция появится в одном из следующих обновлений.',
    basePresetPlaceholder: 'Заглушка базового пресета.',
    renameEventHint: 'Двойной клик для переименования',
    eventTabAdd: 'Добавить событие',
    treeSummary: 'Сводка дерева',
    treeSummaryHint: 'Корень всегда развернут, а глубокие уровни автоматически сворачиваются для читаемости.',
    treeSummaryEmpty: 'Добавьте узлы, чтобы увидеть структуру дерева.',
    treeLeafNode: 'Листовой узел',
    treeExpandChildren: 'Развернуть дочерние узлы',
    treeCollapseChildren: 'Свернуть дочерние узлы',
    treeTypeTooltip: 'Тип: {type}',
    treeNodeIdTooltip: 'Идентификатор узла {id}',
    treeOutlineChance: 'Шанс',
    treeOutlineBranches: 'Ветви',
    treeOutlineIdentifier: 'Идентификатор',
    treeOutlineConditions: 'Условия',
    treeOutlineAction: 'Действие',
    treeUnnamedEventSet: 'безымянный event set',
    treeUnnamedEvent: 'безымянное событие',
    treeNoConditions: 'Без условий',
    treeUnknownItem: 'неизвестный предмет',
    treeUnknownCreature: 'неизвестное существо',
    treeUnknownAffliction: 'неизвестный аффликт',
    treeBranchCount: '{count} ветвь',
    treeBranchCountPlural: '{count} ветвей',
    treeInspectorHint: 'Панорамирование: перетаскивание · Масштаб: колесо мыши · Миникарта: перетаскивание заголовка / изменение размера / колесо мыши · Нажмите узел миникарты для перехода.',
    treeSettingsCollapse: 'Свернуть настройки',
    treeSettingsExpand: 'Развернуть настройки',
    minimapTitle: 'Миникарта',
    chance: 'Шанс',
    mode: 'Режим',
    probability: 'Вероятность',
    weight: 'Вес',
    identifier: 'Идентификатор',
    commonness: 'Частота',
    eventCount: 'Количество событий',
    chooseRandom: 'Выбирать случайно',
    minIntensity: 'Мин. интенсивность',
    maxIntensity: 'Макс. интенсивность',
    minDifficulty: 'Мин. сложность',
    maxDifficulty: 'Макс. сложность',
    allowAtStart: 'Разрешить в начале',
    perWreck: 'На каждый wreck',
    perRuin: 'На каждый ruin',
    perCave: 'На каждую cave',
    ignoreCooldown: 'Игнорировать cooldown',
    triggerCooldown: 'Триггер cooldown',
    identity: 'Идентификация',
    conditions: 'Условия',
    behavior: 'Поведение',
    amount: 'Количество',
    quality: 'Качество',
    count: 'Число',
    spawnLocation: 'Точка спавна',
    spawnLocationInside: 'inside',
    spawnLocationOutside: 'outside',
    spawnLocationNear: 'near',
    label: 'Метка',
    value: 'Значение',
    removeBranch: 'Удалить ветку',
    children: 'Дочерние элементы',
    branch: 'Ветка',
    strength: 'Сила';
