import { sharedLanguageNames } from './shared-language-names.js';

export const zhHansUiDictionary = {
  menuFile: '文件',
  projectImport: '导入项目',
  projectExport: '导出项目',
  importXML: '导入 XML',
  downloadXML: '下载 XML',
  generateXML: '生成 XML',
  menuEdit: '编辑',
  undo: '撤销',
  redo: '重做',
  menuDeleteSelected: '删除所选节点',
  menuDuplicateSelected: '复制所选节点',
  clearEvent: '清空事件',
  menuPresets: '预设',
  menuBasePresets: '基础预设',
  menuOutpostMission: '前哨任务',
  menuWreckExpedition: '沉船探险',
  loadPreset: '加载预设',
  savePreset: '保存为预设',
  managePreset: '管理预设',
  menuTools: '工具',
  simulation: '模拟',
  validateTree: '校验树',
  probabilityAnalysis: '概率分析',
  menuView: '视图',
  menuTheme: '主题模式',
  themeModeDark: '深色',
  themeModeLight: '浅色',
  menuStyle: '样式',
  themeDebug: '标准',
  themeClassicLuna: 'Classic Luna',
  themeNeonOps: 'Neon Ops',
  themeRetroTerminal: 'Retro Terminal',
  themeSoftBloom: 'Soft Bloom',
  menuUiScale: '界面缩放',
  uiScale80: '80%',
  uiScale90: '90%',
  uiScale100: '100%',
  uiScale110: '110%',
  uiScale120: '120%',
  menuHelp: '帮助',
  documentation: '文档',
  openWiki: '打开 Wiki',
  openGithub: '打开 GitHub',
  reportIssue: '报告问题',
  aboutApp: '关于',
  menuSettings: '设置',
  language: '语言',
  openSettingsXmlBehavior: 'XML 行为',
  resetSettings: '重置设置',
  database: '数据库',
  editorModeBasic: '基础',
  editorModeIntermediate: '中级',
  editorModeAdvanced: '高级',
  nodeMode: '节点',
  treeMode: '树',
  editorOperationMode: '编辑器模式',
  editorViewMode: '编辑视图',
  ...sharedLanguageNames
};
