import { sharedLanguageNames } from './shared-language-names.js';

export const zhHantUiDictionary = {
  menuFile: '檔案',
  projectImport: '匯入專案',
  projectExport: '匯出專案',
  importXML: '匯入 XML',
  downloadXML: '下載 XML',
  generateXML: '產生 XML',
  menuEdit: '編輯',
  undo: '復原',
  redo: '重做',
  menuDeleteSelected: '刪除選取節點',
  menuDuplicateSelected: '複製選取節點',
  clearEvent: '清空事件',
  menuPresets: '預設',
  menuBasePresets: '基礎預設',
  menuOutpostMission: '前哨站任務',
  menuWreckExpedition: '沉船探勘',
  loadPreset: '載入預設',
  savePreset: '儲存為預設',
  managePreset: '管理預設',
  menuTools: '工具',
  simulation: '模擬',
  validateTree: '驗證樹',
  probabilityAnalysis: '機率分析',
  menuView: '檢視',
  menuTheme: '主題模式',
  themeModeDark: '深色',
  themeModeLight: '淺色',
  menuStyle: '樣式',
  themeDebug: '標準',
  themeClassicLuna: 'Classic Luna',
  themeNeonOps: 'Neon Ops',
  themeRetroTerminal: 'Retro Terminal',
  themeSoftBloom: 'Soft Bloom',
  menuUiScale: '介面縮放',
  uiScale80: '80%',
  uiScale90: '90%',
  uiScale100: '100%',
  uiScale110: '110%',
  uiScale120: '120%',
  menuHelp: '說明',
  documentation: '文件',
  openWiki: '開啟 Wiki',
  openGithub: '開啟 GitHub',
  reportIssue: '回報問題',
  aboutApp: '關於',
  menuSettings: '設定',
  language: '語言',
  openSettingsXmlBehavior: 'XML 行為',
  resetSettings: '重設設定',
  database: '資料庫',
  editorModeBasic: '基礎',
  editorModeIntermediate: '中階',
  editorModeAdvanced: '進階',
  nodeMode: '節點',
  treeMode: '樹',
  editorOperationMode: '編輯器模式',
  editorViewMode: '編輯視圖',
  ...sharedLanguageNames
};
