// js/lang/en.js — v0.9.109

const LANG_EN = {
  rootLabel: "Root Event",
  successLabel: "Success",
  failureLabel: "Failure",
validationHint: "These checks can be disabled in Settings → XML & Behavior",
  // Кнопки
  generateXML: "Generate XML",
  copyXML: "Copy XML",
  downloadXML: "Download XML",
  export: "Export",
  import: "Import",
  dataBase: "Data Base",

  // Настройки — заголовки и пункты
  settingsTheme: "Theme",
  settingsLanguage: "Language",
  settingsUIScale: "UI Scale",
  settingsNodeDensity: "Node Density",
  settingsNodeStyle: "Node Style",
  settingsShadows: "Shadows",
  settingsGrid: "Background Grid",
  settingsSnap: "Snap to Grid",
  settingsXMLBehavior: "XML & Behavior",
  settingsValidateXML: "Validate XML",
  settingsCheckDuplicates: "Check Duplicate IDs",

  // Режимы вида
  treeView: "Tree View",
  classicView: "Classic",

  // Сообщения
  autoBalanceApplied: "Auto Balance applied!",
  clearAllConfirm: "Clear all?",
  deleteEventConfirm: "Delete event?",
  lastEventWarning: "Cannot delete the last event!",
  xmlCopied: "XML copied to clipboard!",
  xmlCopyFailed: "Failed to copy XML",
  generateFirst: "Generate XML first!",
  importSuccess: "Import completed!",
  importError: "Import error",

  // Ошибки базы
  dbCacheCorrupted: "Items cache corrupted — reloading",
  dbFileNotFound: "items.json not found",
  dbLoadError: "Error loading data/items.json:",
  dbLoadFailed: "Failed to load items database. Check data/items.json",
  dbLoaded: "Database loaded",
  dbItems: "items",

  xmlGeneratedBy: "Generated by Barotrauma RNG Builder v0.9.113",
validationTitle: "XML Validation — issues found:",
validationEmptyEvent: "Event is empty — nothing will spawn",
validationZeroChance: "RNG with 0% or 100% chance — pointless",
validationNoItems: "RNG has no items in branches",
validationDuplicateId: "Duplicate identifier",

  searchPlaceholder: "Search by name, ID or tag..."
};
