// js/lang/en.js — v0.9.200 — ПОЛНАЯ ЛОКАЛИЗАЦИЯ

const LANG_EN = {
  rootLabel: "Root Event",
  successLabel: "Success",
  failureLabel: "Failure",

  // Кнопки
  generateXML: "Generate XML",
  copyXML: "Copy XML",
  downloadXML: "Download XML",
  export: "Export",
  import: "Import",
  dataBase: "Data Base",
  addRNG: "+ RNG",
  addItem: "+ Item",
  addCreature: "+ Creature",
  addAffliction: "+ Affliction",
  clearAll: "Clear",
  autoBalance: "Auto Balance",
  presets: "Presets & Examples",

  // Ноды
  rngAction: "RNG Action",
  spawnItem: "Spawn Item",
  spawnCreature: "Spawn Creature",
  applyAffliction: "Apply Affliction",

  // Параметры
  chance: "Chance",
  count: "Count",
  randomizePosition: "Randomize Position",
  insideSub: "Inside Sub",
  outsideSub: "Outside Sub",
  targetCharacter: "Target: Character",
  targetRandomCrew: "Target: Random Crew",
  targetAllCrew: "Target: All Crew",

  // Настройки
  settingsTheme: "Theme",
  settingsLanguage: "Language",
  settingsUIScale: "UI Scale",
  settingsNodeDensity: "Node Density",
  settingsNodeStyle: "Node Style",
  settingsShadows: "Shadows",
  settingsGrid: "Background Grid",
  settingsSnap: "Snap to Grid",
  settingsXMLBehavior: "XML & Behavior",
  settingsValidateXML: "Validate XML",
  settingsCheckDuplicates: "Check Duplicate IDs",

  // Режимы вида
  treeView: "Tree View",
  classicView: "Classic",

  // Валидация
  validationTitle: "XML Validation — issues found:",
  validationEmptyEvent: "Event is empty — nothing will spawn",
  validationZeroChance: "RNG with 0% or 100% chance — pointless",
  validationNoItems: "RNG has no items in branches",
  validationDuplicateId: "Duplicate identifier",
  validationHint: "These checks can be disabled in Settings → XML & Behavior",

  // Сообщения
  clearAllConfirm: "Clear all?",
  deleteEventConfirm: "Delete event?",
  lastEventWarning: "Cannot delete the last event!",
  xmlGeneratedBy: "Generated by Barotrauma RNG Builder v0.9.200",
  importXML: "Import from XML",
  nothingFound: "Nothing found",
  finalChance: "Final chance"
};
