// js/lang/en.js — 0A2.0.701 — ENGLISH LOCALIZATION

const LANG_EN = {
  /* =========================
     ROOT / TREE
     ========================= */

  rootLabel: "Root Event",
  successLabel: "Success",
  failureLabel: "Failure",

  /* =========================
     BUTTONS
     ========================= */

  generateXML: "Generate XML",
  copyXMLButton: "Copy XML",
  copyXML: "XML copied to clipboard",
  downloadXML: "Download XML",
  export: "Export",
  import: "Import",
  importXML: "Import from XML",

  dataBase: "Database",
  presets: "Presets & Examples",

  addRNG: "+ RNG",
  addItem: "+ Item",
  addCreature: "+ Creature",
  addAffliction: "+ Affliction",

  clearAll: "Clear",
  autoBalance: "Auto Balance",
  addEvent: "+ Add Event",

  /* =========================
     NODE TITLES
     ========================= */

  rngAction: "RNG",
  spawnItem: "Spawn Item",
  spawnCreature: "Spawn Creature",
  applyAffliction: "Apply Affliction",
  unknownNode: "Unknown Node",

  /* =========================
     COMMON PARAMETERS
     ========================= */

  chance: "Chance",
  chanceTooltip: "Probability of this node being executed",

  count: "Count",

  strength: "Strength",
  strengthTooltip: "Effect strength (not duration)",

  /* =========================
     ITEM NODE
     ========================= */

  itemPlaceholder: "revolver",

  itemQuality: "Quality",
  itemQualityTooltip: "Item quality modifier",

  qualityNormal: "Normal",
  qualityGood: "Good",
  qualityExcellent: "Excellent",
  qualityMasterwork: "Masterwork",
  qualityLegendary: "Legendary",

  /* =========================
     CREATURE NODE
     ========================= */

  creaturePlaceholder: "crawler",

  spawnLocation: "Spawn Location",
  spawnLocationTooltip: "Where the creature will appear",

  spawnNear: "Near",
  spawnInside: "Inside",
  spawnOutside: "Outside",

  randomizePosition: "Randomize Position",

  /* =========================
     AFFLICTION NODE
     ========================= */

  afflictionPlaceholder: "bleeding",

  /* =========================
     DB / SEARCH
     ========================= */

  tabAfflictions: "Afflictions",
  tabItems: "Items",
  tabCreatures: "Creatures",

  searchPlaceholder: "Search...",
  nothingFound: "Nothing found",

  dbError: "Database not loaded (check data/*.json files)",

  /* =========================
     SETTINGS
     ========================= */

  settings: "Settings",
  settingsTheme: "Theme",
  settingsLanguage: "Language",
  settingsUIScale: "UI Scale",
  settingsNodeDensity: "Node Density",
  settingsNodeStyle: "Node Style",

  settingsShadows: "Shadows",
  settingsGrid: "Background Grid",
  settingsSnap: "Snap to Grid",

  settingsXMLBehavior: "XML & Behavior",
  settingsValidateXML: "Validate XML",
  settingsCheckDuplicates: "Check Duplicate IDs",

  /* =========================
     VIEW MODES
     ========================= */

  treeView: "Tree View",
  classicView: "Classic View",

  /* =========================
     EVENTS / WARNINGS
     ========================= */

  clearAllConfirm: "Clear all nodes?",
  clearAllDone: "All nodes removed",

  deleteEventConfirm: "Delete event?",
  lastEventWarning: "Cannot delete the last event",

  addEventDone: "Event added",

  presetLoaded: "Preset loaded",
  presetError: "Preset loading error",

  autoBalanceDone: "Auto balance completed",

  xmlGenerated: "XML generated",
  xmlGeneratedBy: "Generated by Barotrauma RNG Builder",

  /* =========================
     DB DETAILS
     ========================= */

  dbDetailID: "ID",
  dbDetailType: "Type",
  dbDetailMaxStrength: "Max Strength",
  dbDetailLimbSpecific: "Limb Specific",
  dbDetailIsBuff: "Buff",

  dbDetailLimbSpecificShort: "Limb",
  dbDetailIsBuffShort: "Buff",

  noDescription: "No description",

  /* =========================
     YES / NO
     ========================= */

  yes: "yes",
  no: "no",

  /* =========================
     EVENT ID
     ========================= */

  eventIdLabel: "Event ID:"
};

window.LANG_EN = LANG_EN;
