const DICTS = {
  en: {
    treeView: 'Tree View',
    classicView: 'Classic View',
    database: 'Database',
    settings: 'Settings',
    theme: 'Base theme',
    themeStyle: 'Style overlay',
    uiScale: 'UI scale',
    grid: 'Background grid',
    projectImport: 'Import project',
    projectExport: 'Export project',
    projectStub: 'Feature stub: project import/export will be added later',
    generateXML: 'Generate XML',
    copyXML: 'Copy XML',
    downloadXML: 'Download XML',
    importXML: 'Import XML',
    addRng: '+ RNG',
    addItem: '+ Item',
    addCreature: '+ Creature',
    addAffliction: '+ Affliction',
    addEvent: '+ Add Event',
    clearEvent: 'Clear Event',
    events: 'Events',
    rootEvent: 'Root Event',
    eventId: 'Event ID:',
    treeEditor: 'Tree node editor',
    selectTreeNode: 'Select a node in tree to edit',
    nodeType: 'Type',
    removeNode: 'Remove node',
    addSuccess: 'Add to Success',
    addFailure: 'Add to Failure',
    language: 'Language',
    xmlGenerated: 'XML generated',
    xmlImported: 'XML imported',
    xmlCopied: 'XML copied',
    xmlDownloaded: 'XML downloaded',
    undo: 'Undo',
    redo: 'Redo',
    chanceColorCoding: 'Chance color coding',
    chanceInputMode: 'Chance input mode',
    chanceModeFraction: 'Fraction (0..1)',
    chanceModePercent: 'Percent (0..100)',
    treeSettings: 'Tree mode settings',
    treeSettingsBasic: 'Basic',
    treeSettingsVisual: 'Visual',
    treeSettingsAdvanced: 'Advanced',
    displayPercent: 'Display %',
    displayHidden: 'Hidden',
    displayLinks: 'On links',
    displayNodes: 'Near nodes',
    displayBoth: 'Both',
    autoChanceMode: 'Auto chance',
    autoChanceOff: 'Disabled',
    autoChanceRoot: 'Split root children equally',
    autoChanceBranch: 'Split each branch equally',
    showPercentOnLinks: 'Show % on links',
    showPercentNearNodes: 'Show % near nodes',
    enableDragDrop: 'Enable drag & drop',
    snapToGrid: 'Snap to grid',
    showTreeGrid: 'Show tree grid',
    showMinimap: 'Show minimap',
    colorMinimapBranches: 'Path coloring in minimap',
    minimapPathColoring: 'Path coloring in minimap',
    minimapSizePreset: 'Size preset',
    minimapScale: 'Minimap scale',
    minimapMode: 'Minimap mode',
    minimapModeStandard: 'Standard',
    minimapFocusMode: 'Focus / active path',
    minimapTypeMode: 'Type mode',
    minimapTypeDots: 'Dots',
    minimapTypeColor: 'Type colors',
    minimapTypeIcon: 'Type icons',
    minimapTypeIconColor: 'Icons + colors',
    minimapSizeSmall: 'Small',
    minimapSizeMedium: 'Medium',
    minimapSizeLarge: 'Large',
    minimapSizeAuto: 'Auto',
    minimapColorSuccessFailure: 'Success / Failure',
    minimapColorProbability: 'Probability',
    uiLevel: 'UI Level',
    uiLevelBasic: 'Basic',
    uiLevelAdvanced: 'Advanced',
    modeSection: 'Mode',
    treeSettingsEditing: 'Editing',
    visualSection: 'Visual',
    debugSection: 'Debug',
    runAutoLayout: 'Run auto-layout',
    exportTree: 'Export Tree',
    exportMinimap: 'Export Minimap',
    exportAsSvg: 'Export as SVG',
    exportAsPng: 'Export as PNG',
    hintAutoChance: 'Automatically distributes branch chances based on selected strategy.',
    hintDisplayPercent: 'Controls where probability labels are displayed in the main tree.',
    hintPathColoring: 'Choose how minimap paths should be colorized.',
    showBranchNodes: 'Show Success/Failure intermediate nodes',
    showDebugBounds: 'Show debug overlays',
    gridSize: 'Grid size',
    autoLayout: 'Auto-layout',
    collapseSubtree: 'Collapse subtree',
    expandSubtree: 'Expand subtree',
  },
  ru: {
    treeView: 'Древо',
    classicView: 'Классический вид',
    database: 'База данных',
    settings: 'Настройки',
    theme: 'Базовая тема',
    themeStyle: 'Надстройка темы',
    uiScale: 'Масштаб UI',
    grid: 'Фоновая сетка',
    projectImport: 'Импорт проекта',
    projectExport: 'Экспорт проекта',
    projectStub: 'Заглушка: импорт/экспорт проекта будет добавлен позже',
    generateXML: 'Сгенерировать XML',
    copyXML: 'Копировать XML',
    downloadXML: 'Скачать XML',
    importXML: 'Импорт XML',
    addRng: '+ RNG',
    addItem: '+ Предмет',
    addCreature: '+ Существо',
    addAffliction: '+ Эффект',
    addEvent: '+ Добавить событие',
    clearEvent: 'Очистить событие',
    events: 'События',
    rootEvent: 'Корневое событие',
    eventId: 'ID события:',
    treeEditor: 'Редактор нод дерева',
    selectTreeNode: 'Выберите ноду в дереве для редактирования',
    nodeType: 'Тип',
    removeNode: 'Удалить ноду',
    addSuccess: 'Добавить в Success',
    addFailure: 'Добавить в Failure',
    language: 'Язык',
    xmlGenerated: 'XML сгенерирован',
    xmlImported: 'XML импортирован',
    xmlCopied: 'XML скопирован',
    xmlDownloaded: 'XML скачан',
    undo: 'Отменить',
    redo: 'Повторить',
    chanceColorCoding: 'Цветовая кодировка шансов',
    chanceInputMode: 'Формат ввода шанса',
    chanceModeFraction: 'Дробь (0..1)',
    chanceModePercent: 'Проценты (0..100)',
    treeSettings: 'Настройки Tree mod',
    treeSettingsBasic: 'Основные',
    treeSettingsVisual: 'Визуал',
    treeSettingsAdvanced: 'Расширенные',
    displayPercent: 'Отображение %',
    displayHidden: 'Скрыть',
    displayLinks: 'На линиях',
    displayNodes: 'Возле нод',
    displayBoth: 'Оба варианта',
    autoChanceMode: 'Авто-расчет шанса',
    autoChanceOff: 'Отключен',
    autoChanceRoot: 'Равномерно только для корня',
    autoChanceBranch: 'Равномерно для каждой ветки',
    showPercentOnLinks: 'Показывать % на линиях',
    showPercentNearNodes: 'Показывать % возле нод',
    enableDragDrop: 'Включить Drag & Drop',
    snapToGrid: 'Привязка к сетке',
    showTreeGrid: 'Показывать сетку дерева',
    showMinimap: 'Показывать мини-карту',
    colorMinimapBranches: 'Подсветка путей в миникарте',
    minimapPathColoring: 'Подсветка путей в миникарте',
    minimapSizePreset: 'Пресет размера',
    minimapScale: 'Масштаб миникарты',
    minimapMode: 'Режим мини-карты',
    minimapModeStandard: 'Стандартный',
    minimapFocusMode: 'Фокус / активный путь',
    minimapTypeMode: 'Режим точек',
    minimapTypeDots: 'Точки',
    minimapTypeColor: 'Цвета типов',
    minimapTypeIcon: 'Иконки типов',
    minimapTypeIconColor: 'Иконки + цвета',
    minimapSizeSmall: 'Маленький',
    minimapSizeMedium: 'Средний',
    minimapSizeLarge: 'Большой',
    minimapSizeAuto: 'Авто',
    minimapColorSuccessFailure: 'Успех / неудача',
    minimapColorProbability: 'Вероятность',
    uiLevel: 'Уровень интерфейса',
    uiLevelBasic: 'Базовый',
    uiLevelAdvanced: 'Расширенный',
    modeSection: 'Режим',
    treeSettingsEditing: 'Редактирование',
    visualSection: 'Визуал',
    debugSection: 'Отладка',
    runAutoLayout: 'Запустить авто-layout',
    exportTree: 'Экспорт дерева',
    exportMinimap: 'Экспорт миникарты',
    exportAsSvg: 'Экспорт в SVG',
    exportAsPng: 'Экспорт в PNG',
    hintAutoChance: 'Автоматически распределяет шансы веток по выбранной стратегии.',
    hintDisplayPercent: 'Определяет, где показывать подписи вероятностей в основном дереве.',
    hintPathColoring: 'Выберите, как раскрашивать пути на миникарте.',
    showBranchNodes: 'Показывать промежуточные ноды Success/Failure',
    showDebugBounds: 'Показывать debug-оверлеи',
    gridSize: 'Размер сетки',
    autoLayout: 'Авто-layout',
    collapseSubtree: 'Свернуть поддерево',
    expandSubtree: 'Развернуть поддерево',
  }
};

let currentLang = localStorage.getItem('lang') || 'en';
const listeners = new Set();

export function t(key) {
  return DICTS[currentLang]?.[key] || DICTS.en[key] || key;
}

export function getLang() {
  return currentLang;
}

export function setLang(lang) {
  if (!DICTS[lang]) return;
  currentLang = lang;
  localStorage.setItem('lang', lang);
  listeners.forEach(listener => listener(lang));
}

export function onLangChange(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function applyLocalization(root = document) {
  root.querySelectorAll('[data-l10n]').forEach(el => {
    const key = el.dataset.l10n;
    if (key) el.textContent = t(key);
  });

  root.querySelectorAll('[data-l10n-placeholder]').forEach(el => {
    const key = el.dataset.l10nPlaceholder;
    if (key) el.placeholder = t(key);
  });
}
