import { getAppSetting, setAppSetting } from '../state/app-settings.js';

const DICTS = {
  en: {
    treeView: 'Tree View',
    classicView: 'Classic View',
    database: 'Database',
    documentation: 'Documentation',
    settings: 'Settings',
    theme: 'Base theme',
    themeMode: 'Theme mode',
    themeModeDark: 'Dark',
    themeModeLight: 'Light',
    themeDebug: 'Normal',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    themeStyle: 'Style overlay',
    uiScale: 'UI scale',
    grid: 'Background grid',
    projectImport: 'Import project',
    projectExport: 'Export project',
    projectStub: 'Feature stub: project import/export will be added later',
    generateXML: 'Generate XML',
    copyXML: 'Copy XML',
    downloadXML: 'Download XML',
    importXML: 'Import XML',
    addRng: '+ RNG',
    addItem: '+ Item',
    addCreature: '+ Creature',
    addAffliction: '+ Affliction',
    addEvent: '+ Add Event',
    clearEvent: 'Clear Event',
    events: 'Events',
    rootEvent: 'Root Event',
    eventId: 'Event ID:',
    treeEditor: 'Tree node editor',
    selectTreeNode: 'Select a node in tree to edit',
    nodeType: 'Type',
    removeNode: 'Remove node',
    addSuccess: 'Add to Success',
    addFailure: 'Add to Failure',
    language: 'Language',
    clearCache: 'Clear cache',
    langEnglish: 'English',
    langRussian: 'Русский',
    langSimplifiedChinese: '简体中文',
    langTraditionalChinese: '繁體中文',
    langFrench: 'Français',
    langSpanish: 'Español',
    langGerman: 'Deutsch',
    langPolish: 'Polski',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale125: '125%',
    themeStyleCompact: 'Compact',
    themeStyleBalanced: 'Balanced',
    themeStyleSoft: 'Soft',
    xmlGenerated: 'XML generated',
    xmlImported: 'XML imported',
    xmlCopied: 'XML copied',
    xmlDownloaded: 'XML downloaded',
    undo: 'Undo',
    redo: 'Redo',
    chanceColorCoding: 'Chance color coding',
    chanceInputMode: 'Chance input mode',
    chanceModeFraction: 'Fraction (0..1)',
    chanceModePercent: 'Percent (0..100)',
    treeSettings: 'Tree mode settings',
    treeSettingsBasic: 'Basic',
    treeSettingsVisual: 'Visual',
    treeSettingsAdvanced: 'Advanced',
    displayPercent: 'Display %',
    displayHidden: '∅',
    displayLinks: '⇄',
    displayNodes: '⋈',
    displayBoth: '⧉',
    displayHiddenHint: 'Hide probability labels',
    displayLinksHint: 'Show on links',
    displayNodesHint: 'Show near nodes',
    displayBothHint: 'Show on links and near nodes',
    autoChanceMode: 'Auto chance',
    autoChanceOff: 'Disabled',
    autoChanceRoot: 'Split root children equally',
    autoChanceBranch: 'Split each branch equally',
    showPercentOnLinks: 'Show % on links',
    showPercentNearNodes: 'Show % near nodes',
    enableDragDrop: 'Enable drag & drop',
    snapToGrid: 'Snap to grid',
    showTreeGrid: 'Show tree grid',
    showMinimap: 'Show minimap',
    colorMinimapBranches: 'Path coloring in minimap',
    minimapPathColoring: 'Path coloring in minimap',
    minimapSizePreset: 'Size preset',
    minimapScale: 'Minimap scale',
    minimapMode: 'Minimap mode',
    minimapModeStandard: 'Standard',
    minimapFocusMode: 'Focus / active path',
    minimapTypeMode: 'Type mode',
    minimapTypeDots: 'Dots',
    minimapTypeColor: 'Type colors',
    minimapTypeIcon: 'Type icons',
    minimapTypeIconColor: 'Icons + colors',
    minimapSizeSmall: 'Small',
    minimapSizeMedium: 'Medium',
    minimapSizeLarge: 'Large',
    minimapSizeAuto: 'Auto',
    minimapColorSuccessFailure: 'Success / Failure',
    minimapColorProbability: 'Probability',
    uiLevel: 'UI Level',
    uiLevelBasic: 'Basic',
    uiLevelAdvanced: 'Advanced',
    modeSection: 'Mode',
    treeSettingsEditing: 'Editing',
    visualSection: 'Visual',
    debugSection: 'Debug',
    runAutoLayout: 'Run auto-layout',
    exportTree: 'Export Tree',
    exportMinimap: 'Export Minimap',
    exportAsSvg: 'Export as SVG',
    exportAsPng: 'Export as PNG',
    hintAutoChance: 'Automatically distributes branch chances based on selected strategy.',
    hintDisplayPercent: 'Controls where probability labels are displayed in the main tree.',
    hintPathColoring: 'Choose how minimap paths should be colorized.',
    showBranchNodes: 'Show Success/Failure intermediate nodes',
    showDebugBounds: 'Show debug overlays',
    gridSize: 'Grid size',
    autoLayout: 'Auto-layout',
    collapseSubtree: 'Collapse subtree',
    expandSubtree: 'Expand subtree',
    dropZoneSuccessHint: 'Drop here to insert into Success branch',
    dropZoneFailureHint: 'Drop here to insert into Failure branch',
    confirmRemoveEvent: 'Delete this event?',
    smoothTreePaths: 'Smooth links',
    runSimulation: 'Run Simulation',
    simulation: 'Simulation',
    validateTree: 'Validate Tree',
    toggleHeatmap: 'Heatmap',
    searchNodes: 'Search Nodes',
    quickAdd: 'Quick Add',
    nodeMode: 'Node',
    treeMode: 'Tree',
    search: 'Search',
    iterations: 'Iterations',
    seed: 'Seed',
    confirmClearEvent: 'Clear the current event?',
    confirmRemoveNode: 'Remove this node?',
    importXmlPlaceholderDescription: 'Placeholder import dialog: upload an XML file, drag it here, or paste XML directly. Import logic will be added later.',
    importXmlDropTitle: 'Drop XML file here or click to upload',
    importXmlDropHint: 'Accepted for now: .xml files (placeholder only)',
    importXmlNoFile: 'No file selected',
    importXmlPasteLabel: 'Paste XML code',
    importXmlPastePlaceholder: '<Event identifier="example">\n  ...\n</Event>',
    importXmlActionPlaceholder: 'Import placeholder',
    close: 'Close',
    localizationPlaceholder: 'Language placeholder: localization is not implemented yet.',
  },
  ru: {
    treeView: 'Древо',
    classicView: 'Классический вид',
    database: 'База данных',
    documentation: 'Документация',
    settings: 'Настройки',
    theme: 'Базовая тема',
    themeMode: 'Режим темы',
    themeModeDark: 'Тёмный',
    themeModeLight: 'Светлый',
    themeDebug: 'Normal',
    themeClassicLuna: 'Classic Luna',
    themeNeonOps: 'Neon Ops',
    themeRetroTerminal: 'Retro Terminal',
    themeSoftBloom: 'Soft Bloom',
    themeStyle: 'Надстройка темы',
    uiScale: 'Масштаб UI',
    grid: 'Фоновая сетка',
    projectImport: 'Импорт проекта',
    projectExport: 'Экспорт проекта',
    projectStub: 'Заглушка: импорт/экспорт проекта будет добавлен позже',
    generateXML: 'Сгенерировать XML',
    copyXML: 'Копировать XML',
    downloadXML: 'Скачать XML',
    importXML: 'Импорт XML',
    addRng: '+ RNG',
    addItem: '+ Предмет',
    addCreature: '+ Существо',
    addAffliction: '+ Эффект',
    addEvent: '+ Добавить событие',
    clearEvent: 'Очистить событие',
    events: 'События',
    rootEvent: 'Корневое событие',
    eventId: 'ID события:',
    treeEditor: 'Редактор нод дерева',
    selectTreeNode: 'Выберите ноду в дереве для редактирования',
    nodeType: 'Тип',
    removeNode: 'Удалить ноду',
    addSuccess: 'Добавить в Success',
    addFailure: 'Добавить в Failure',
    language: 'Язык',
    clearCache: 'Очистить кэш',
    langEnglish: 'English',
    langRussian: 'Русский',
    langSimplifiedChinese: '简体中文',
    langTraditionalChinese: '繁體中文',
    langFrench: 'Français',
    langSpanish: 'Español',
    langGerman: 'Deutsch',
    langPolish: 'Polski',
    uiScale90: '90%',
    uiScale100: '100%',
    uiScale110: '110%',
    uiScale125: '125%',
    themeStyleCompact: 'Компактная',
    themeStyleBalanced: 'Сбалансированная',
    themeStyleSoft: 'Мягкая',
    xmlGenerated: 'XML сгенерирован',
    xmlImported: 'XML импортирован',
    xmlCopied: 'XML скопирован',
    xmlDownloaded: 'XML скачан',
    undo: 'Отменить',
    redo: 'Повторить',
    chanceColorCoding: 'Цветовая кодировка шансов',
    chanceInputMode: 'Формат ввода шанса',
    chanceModeFraction: 'Дробь (0..1)',
    chanceModePercent: 'Проценты (0..100)',
    treeSettings: 'Настройки Tree mod',
    treeSettingsBasic: 'Основные',
    treeSettingsVisual: 'Визуал',
    treeSettingsAdvanced: 'Расширенные',
    displayPercent: 'Отображение %',
    displayHidden: '∅',
    displayLinks: '⇄',
    displayNodes: '⋈',
    displayBoth: '⧉',
    displayHiddenHint: 'Скрыть подписи вероятности',
    displayLinksHint: 'Показывать на линиях',
    displayNodesHint: 'Показывать возле нод',
    displayBothHint: 'Показывать и на линиях, и возле нод',
    autoChanceMode: 'Авто-расчет шанса',
    autoChanceOff: 'Отключен',
    autoChanceRoot: 'Равномерно только для корня',
    autoChanceBranch: 'Равномерно для каждой ветки',
    showPercentOnLinks: 'Показывать % на линиях',
    showPercentNearNodes: 'Показывать % возле нод',
    enableDragDrop: 'Включить Drag & Drop',
    snapToGrid: 'Привязка к сетке',
    showTreeGrid: 'Показывать сетку дерева',
    showMinimap: 'Показывать мини-карту',
    colorMinimapBranches: 'Подсветка путей в миникарте',
    minimapPathColoring: 'Подсветка путей в миникарте',
    minimapSizePreset: 'Пресет размера',
    minimapScale: 'Масштаб миникарты',
    minimapMode: 'Режим мини-карты',
    minimapModeStandard: 'Стандартный',
    minimapFocusMode: 'Фокус / активный путь',
    minimapTypeMode: 'Режим точек',
    minimapTypeDots: 'Точки',
    minimapTypeColor: 'Цвета типов',
    minimapTypeIcon: 'Иконки типов',
    minimapTypeIconColor: 'Иконки + цвета',
    minimapSizeSmall: 'Маленький',
    minimapSizeMedium: 'Средний',
    minimapSizeLarge: 'Большой',
    minimapSizeAuto: 'Авто',
    minimapColorSuccessFailure: 'Успех / неудача',
    minimapColorProbability: 'Вероятность',
    uiLevel: 'Уровень интерфейса',
    uiLevelBasic: 'Базовый',
    uiLevelAdvanced: 'Расширенный',
    modeSection: 'Режим',
    treeSettingsEditing: 'Редактирование',
    visualSection: 'Визуал',
    debugSection: 'Отладка',
    runAutoLayout: 'Запустить авто-layout',
    exportTree: 'Экспорт дерева',
    exportMinimap: 'Экспорт миникарты',
    exportAsSvg: 'Экспорт в SVG',
    exportAsPng: 'Экспорт в PNG',
    hintAutoChance: 'Автоматически распределяет шансы веток по выбранной стратегии.',
    hintDisplayPercent: 'Определяет, где показывать подписи вероятностей в основном дереве.',
    hintPathColoring: 'Выберите, как раскрашивать пути на миникарте.',
    showBranchNodes: 'Показывать промежуточные ноды Success/Failure',
    showDebugBounds: 'Показывать debug-оверлеи',
    gridSize: 'Размер сетки',
    autoLayout: 'Авто-layout',
    collapseSubtree: 'Свернуть поддерево',
    expandSubtree: 'Развернуть поддерево',
    dropZoneSuccessHint: 'Отпустите сюда, чтобы вставить в ветку Success',
    dropZoneFailureHint: 'Отпустите сюда, чтобы вставить в ветку Failure',
    confirmRemoveEvent: 'Удалить это событие?',
    smoothTreePaths: 'Плавные линии связей',
    runSimulation: 'Запуск симуляции',
    simulation: 'Simulation',
    validateTree: 'Проверить дерево',
    toggleHeatmap: 'Тепловая карта',
    searchNodes: 'Поиск нод',
    quickAdd: 'Быстро добавить',
    nodeMode: 'Ноды',
    treeMode: 'Дерево',
    search: 'Поиск',
    iterations: 'Итерации',
    seed: 'Seed',
    confirmClearEvent: 'Очистить текущее событие?',
    confirmRemoveNode: 'Удалить эту ноду?',
    importXmlPlaceholderDescription: 'Диалог импорта пока работает как плейсхолдер: загрузите XML-файл, перетащите его сюда или вставьте XML напрямую. Логика импорта появится позже.',
    importXmlDropTitle: 'Перетащите XML-файл сюда или нажмите для загрузки',
    importXmlDropHint: 'Пока принимаются только .xml файлы (плейсхолдер)',
    importXmlNoFile: 'Файл не выбран',
    importXmlPasteLabel: 'Вставьте XML-код',
    importXmlPastePlaceholder: '<Event identifier="example">\n  ...\n</Event>',
    importXmlActionPlaceholder: 'Плейсхолдер импорта',
    close: 'Закрыть',
    localizationPlaceholder: 'Плейсхолдер языка: локализация пока не реализована.',
  }
};

let currentLang = getAppSetting('lang') || 'en';
const listeners = new Set();

export function t(key) {
  return DICTS[currentLang]?.[key] || DICTS.en[key] || key;
}

export function getLang() {
  return currentLang;
}

export function setLang(lang) {
  if (!DICTS[lang]) return;
  currentLang = lang;
  setAppSetting('lang', lang);
  listeners.forEach(listener => listener(lang));
}

export function onLangChange(listener) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function applyLocalization(root = document) {
  root.querySelectorAll('[data-l10n]').forEach(el => {
    const key = el.dataset.l10n;
    if (key) el.textContent = t(key);
  });

  root.querySelectorAll('[data-l10n-placeholder]').forEach(el => {
    const key = el.dataset.l10nPlaceholder;
    if (key) el.placeholder = t(key);
  });
}
